Join макросы
adventum/dbt-etlcraft pull request #1
Opened 2023-11-17 11:05 UTC by palizunov

2023-11-17 11:29 UTC, sckol requested changes

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_event.sql
> +{% macro join_mobile_event( source_types, streams, templates) %}
слой join объединяет данные в рамках одного источника-шаблона. Поэтому должно быть join_название_пайплайна_назвениеисточника_название_темплейта, то есть join_mobileevents_appflyer_default(streams).

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_event.sql
> +        {% if stream == 'in_app_events' %}
У нас есть обязательные стримы без которых запрос не построится. В данном случае это in_app_events. Это проверяется еще на уровне дага. Поэтому проверять его не стоит даже. Возможно, потом мы будем вообще в streams передавать только необязательные стримы.

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_event.sql
> +            WITH install as (
Причем тут install?

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_event.sql
> +                --test query_type
Это зачем?

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_event.sql
> +                    __datetime AS event_time,
__datetime давай оставлять как есть, мы по нему потом order_by делаем

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_event.sql
> +                    toDate(install_time) AS install_date,
Каст к дате - это было требование для конкретной задачи выгрузки в шитс, надо это на следующих слоях делать

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_event.sql
> +        {% elif stream == 'post_attribution_in_app_events' %}
Даже итерироваться не нужно по streams, достаточно if 'post_attribution_in_app_events' in streams

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_event.sql
> +    {% if "in_app_events" in streams %}
Можно было даже не делать CTE, а в начале добавить переменную has_posattribution, если она true, то добавить полей типа is_fraud в SELECT и JOIN в конце

2023-11-17 11:29 UTC, sckol commented on macros/join_pipeline_name.sql
> +
Вроде на созвоне решили, что такое вроде и не нужно, мы сразу будем в даге генерировать нужное название макроса

2023-11-17 11:29 UTC, sckol commented on macros/join_mobile_install.sql
> +{% macro join_mobile_install( source_types, streams, templates) %}
Те же самые комменты

2023-11-17 13:36 UTC, palizunov commented
test

2023-11-17 13:51 UTC, sckol commented on macros/join_mobile_event.sql
> +{% macro join_mobile_event( source_types, streams, templates) %}
Давай подумаем, какие у нас могут быть ситуации на примере Яндекс.Директа.

1. Кому-то нужна просто статистика по кампаниям
2. Кому-то нужна статистика по кампаниям и по ключевым словам (поскольку ключевые слова есть не в каждом объявлении, то это будет UNION статы по кампаниям со статой по ключевым словам с дополнительным полем report_type
3. Кому-то нужны просто тексты объявлений, которые можно забрать из стрима с настройками РК
4. Кому-то стата по текстам объявлений

По идее, все 4 случая можно покрыть одним шаблоном. Назовем его default. Этот шаблон, если включен стрим по костам кампаний или ключевых слов, добавляет пайплайн adcost. Тут понятие обязательного стрима размывается, потому что можно указать либо только кампании, либо только ключевые слова, либо и то, и другое вместе. Макрос проверяет, какие стримы есть и делает UNION, если их две. Если среди стримов есть настройки объявлений, то еще делается джойн с ним.

Второй пайплайн называется adsettings и включается, если среди стримов есть настройки объявлений. Он содержит просто настройки. 

Получается, если у нас кейс №4, у нас создастся лишний пайплайн - сами настройки могут быть нам и не нужны. Решать это введением другого шаблона как-то странно. Возможно, шаблоны здесь вообще не надо передавать, а надо ввести настройки пайплайна, которым можно задать - ну не знаю где - в даге, в интерфейсе. Среди настроек может быть например disable, чтобы определенный пайплайн не включался.

Поэтому возможно макрос и не должен содержать имя темплейта, зато должен содержать словарь с дополнительными аргументами params

2023-11-20 12:10 UTC, palizunov commented on macros/join_mobile_event.sql
> +    {% if "in_app_events" in streams %}
Это имеешь в виду?
```sql
SELECT 
    x.__datetime AS install_time
    ,x.*EXCEPT(__emitted_at, __normalized_at)
{% if "post_attribution_installs" in streams %} 
    ,y.appsflyer_id = x.appsflyer_id as is_fraud
    ,detection_date
    ,fraud_reason	
    ,fraud_reasons	
    ,fraud_sub_reason
{% endif %}        
FROM {{ref('incremental_' ~ templates ~ '_installs')}} as x
{% if "post_attribution_installs" in streams %} 
left join {{ref('incremental_' ~ templates ~ '_post_attribution_installs')}} as y
    using(appsflyer_id)
{% endif %}
```

2023-11-20 16:05 UTC, sckol requested changes

2023-11-20 16:05 UTC, sckol commented on macros/join_mobileevents.sql
> +{% macro join_mobileevents(source_types, streams, templates, params = none) %}
source_types и templates заменить на template

2023-11-20 16:05 UTC, sckol commented on macros/join_mobileevents.sql
> +    x.__datetime AS event_time
__datetime давай оставим как есть

2023-11-21 11:21 UTC, sckol requested changes

2023-11-21 11:21 UTC, sckol commented on macros/join_mobileevents.sql
> +{% macro join_mobileevents(streams, templates, params = none) %}
template должен идти в единственном числе
template по логике более важный параметр, поэтому он должен идти первым
params предлагаю снова убрать, потому что пришла другая идея, напишу в отдельной задаче

2023-11-21 11:21 UTC, sckol commented on macros/join_mobileevents.sql
> +    ,x.*EXCEPT(__emitted_at, __normalized_at)
запятая не нужна, вместо x и y лучше использовать более осмысленные имена

2023-12-25 11:13 UTC, sckol approved these changes

2023-12-25 11:14 UTC, sckol commented
Добавлен шаблон для шага join

2023-12-25 11:14 UTC, merged